### ISSUE TITLE
Add a Barbs element

### ISSUE THREAD

**Issue by philippjfr** [holoviz/geoviews#133]
Since we have a VectorField element now it would be nice if we had a similar Barbs element. Cartopy and matplotlib already support drawing barbs and it shouldn't be too difficult to draw barbs using bokeh too.

Here's what barbs look like in cartopy:

![image](https://user-images.githubusercontent.com/1550771/35875078-20fbf7e0-0b66-11e8-9a7a-fc5054499bc6.png)

**Comment by jbednar** [comment]
Sounds good.  For clarity, it would be helpful to paste a screenshot or link to another plotting program's barb glyphs to show what functionality would be expected, more concretely.

**Comment by acrosby** [comment]
I am interested in visualizing points with barbs in addition to the vector field example above.

What might be involved in, or where to start, getting an implementation equivalent to MPL's (https://matplotlib.org/api/_as_gen/matplotlib.pyplot.barbs.html#matplotlib.pyplot.barbs) over to bokeh/geoviews?

Here's MPL's barb demo (https://matplotlib.org/gallery/images_contours_and_fields/barb_demo.html#sphx-glr-gallery-images-contours-and-fields-barb-demo-py):
![](https://matplotlib.org/_images/sphx_glr_barb_demo_001.png)

**Comment by jbednar** [comment]
I've been wondering when someone would start asking for this! :-)

**Comment by dwr-psandhu** [comment]
@jbednar Given mpl's implementation of barbs doesn't this issue belong to holoviews? I read the previous discussion that closed holoviz/holoviews#3901 based on cartopy's implementation.
