### ISSUE TITLE
BBoxTileSource Support

### ISSUE THREAD

**Issue by ktrapeznikov** [holoviz/geoviews#149]
I have couple tile servers that serve map tiles in the bounding box format. I have used them with bokeh using their BBoxTileSource class.

Is there an easy way to get them to work in geoviews?

**Comment by jbednar** [comment]
Based on the Bokeh docs, it looks to me like it should work fine if you use the right URL string, i.e. something like `http://your.custom.tile.service?bbox={XMIN},{YMIN},{XMAX},{YMAX}`.  If it doesn't, let us know.

**Comment by philippjfr** [comment]
This is now supported but it would be good to document it properly with some examples of different types of tile sources.

**Comment by ktrapeznikov** [comment]
I don’t know of any public ones. We just have couple legacy tile servers that we run locally.
