### ISSUE TITLE
Speeding up projected maps in geoviews?

### ISSUE THREAD

**Issue by rsignell-usgs** [holoviz/geoviews#230]
I'm visualizing public Landsat data with `hvplot.xarray` but I think this is likely a `geoviews` issue.   

It takes about **3 seconds** to render an image when not using the `crs`:
![2018-09-19_17-11-28](https://user-images.githubusercontent.com/1872600/45781830-2381e400-bc2f-11e8-85c8-194ea98ab7a1.jpg)

It takes about  **3 minutes** to render an image when using the `crs`:
![2018-09-19_17-12-26](https://user-images.githubusercontent.com/1872600/45781856-35638700-bc2f-11e8-8809-592e4e5a9aa5.jpg)

Without `crs` it's using my dask cluster, but with `crs` it does not use the cluster. 

This is the code I'm using:

```python
import rasterio 
import xarray as xr
import hvplot.xarray
from dask.distributed import Client, progress
import cartopy.crs as ccrs

client = Client()

image_url = 'https://storage.googleapis.com/gcp-public-data-landsat/LC08/01/047/027/LC08_L1TP_047027_20130421_20170310_01_T1/LC08_L1TP_047027_20130421_20170310_01_T1_B4.TIF'

da = xr.open_rasterio(image_url, chunks={'band': 1, 'x': 2048, 'y': 2048})

band1 = da.sel(band=1).persist()

display(band1.hvplot(rasterize=True, width=600, height=400, cmap='viridis'))

crs = ccrs.UTM(zone='10n')
display(band1.hvplot(crs=crs, rasterize=True, width=600, height=400, cmap='viridis'))
```
Here is the [notebook](https://nbviewer.jupyter.org/gist/rsignell-usgs/438f5b895725bac2de4626097724fcfa).

Is this expected?

Is there anything I can do to speed up visualization with `crs` specified?

**Comment by rsignell-usgs** [comment]
I heard offline from @dharhas that this is a Cartopy issue.    @pelson, can you confirm?

**Comment by philippjfr** [comment]
Apologies for not replying sooner, I do think this is down to cartopy but it's also possible that I'm using a suboptimal codepath. To project images we are currently calling ``cartopy.img_transform.warp_array``, which I think is the bottleneck here.

**Comment by jbednar** [comment]
Can the data in the image be projected ahead of time, before displaying it?

**Comment by philippjfr** [comment]
Yes, ``gv.project`` will do that for you but that's still 3 minutes and therefore way too long.

**Comment by rsignell-usgs** [comment]
So I'm guessing `gv.project` does not use Dask either, right?

**Comment by philippjfr** [comment]
Thanks, for your experiments, I'll play around with this now. The equivalent operation using geoviews which ends up making a call to ``cartopy.img_transform.warp_array`` is this: 

```python
import geoviews as gv
import cartopy.crs as ccrs
img = gv.load_tiff('/Users/philippjfr/Downloads/LC08_L1TP_047027_20130421_20170310_01_T1_B4.TIF')
projected = gv.project(img, projection=ccrs.PlateCarree())
```

**Comment by philippjfr** [comment]
Here's the output of profiling the project operation with ``%%prun``:

```
         15066 function calls (14817 primitive calls) in 242.420 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  242.420  242.420 {built-in method builtins.exec}
        1    0.000    0.000  242.420  242.420 <string>:2(<module>)
        1    0.000    0.000  242.420  242.420 parameterized.py:2416(__new__)
      2/1    0.000    0.000  242.419  242.419 operation.py:146(__call__)
      2/1    0.000    0.000  242.419  242.419 operation.py:113(_apply)
        1    0.000    0.000  242.419  242.419 projection.py:396(_process)
        6    0.000    0.000  242.416   40.403 dimension.py:713(map)
        1    0.143    0.143  242.414  242.414 projection.py:292(_process)
        1    1.119    1.119  242.132  242.132 img_transform.py:122(warp_array)
        1   21.111   21.111  240.060  240.060 img_transform.py:220(regrid)
        1  115.320  115.320  115.320  115.320 {method 'query' of 'scipy.spatial.ckdtree.cKDTree' objects}
        4   98.791   24.698   98.791   24.698 {method 'transform_points' of 'cartopy._crs.CRS' objects}
```

**Comment by rsignell-usgs** [comment]
Wow @philippjfr , looks like we have some room for improvement!   Great!
cc @josef-ebd

**Comment by rsignell-usgs** [comment]
@philippjfr [this Cartopy PR](https://github.com/SciTools/cartopy/pull/1150) from @QuLogic looks promising!

**Comment by philippjfr** [comment]
Definitely some solid improvement there, but not enough to make it very usable:

Using scipy's kdtree:

```
        1  115.320  115.320  115.320  115.320 {method 'query' of 'scipy.spatial.ckdtree.cKDTree' objects}
```

using pykdtree:

```
        1   53.287   53.287   53.287   53.287 {method 'query' of 'pykdtree.kdtree.KDTree' objects}
```

**Comment by philippjfr** [comment]
Actually, after calling ``rasterize`` it's pretty usable, no reason to project the whole image afterall.

**Comment by philippjfr** [comment]
Okay, I'm now wondering whether hvplot is doing something quite suboptimal, using geoviews directly things are pretty quick:

```python
import geoviews as gv
from holoviews.operation.datashader import rasterize
gv.extension('bokeh')

tiff = gv.load_tiff('/Users/philippjfr/Downloads/LC08_L1TP_047027_20130421_20170310_01_T1_B4.TIF')
rasterize(tiff)
```

**Comment by philippjfr** [comment]
I've opened https://github.com/pyviz/hvplot/pull/106 to add the project=True/False argument to hvplot.

**Comment by rsignell-usgs** [comment]
Here's my example with the latest release, just to show it's working in seconds now!

![2018-11-15_16-43-35](https://user-images.githubusercontent.com/1872600/48583675-b9678180-e8f5-11e8-9e24-3dffde031408.png)
