### ISSUE TITLE
Hover coordinates should be in lat/lon rather than projected coordinate system

### ISSUE THREAD

**Issue by ahuang11** [holoviz/geoviews#251]
```
import os
import xarray as xr
import holoviews as hv
import geoviews as gv
import holoplot.xarray
from cartopy import crs

hv.extension('bokeh')

img_opts_dict = dict(
    projection=crs.Robinson(),
    colorbar=True,
    show_grid=True
)

os.system(
    'wget -nc '
    'ftp://ftp.cdc.noaa.gov/'
    'Datasets/ncep.reanalysis.dailyavgs/'
    'surface/'
    'air.sig995.2018.nc'
)
coast = gv.feature.coastline()

obs_ds = xr.open_dataset('air.sig995.2018.nc')
img = obs_ds.holoplot.image(x='lon', y='lat', z='air', groupby='time', geo=True).options(**img_opts_dict)

from bokeh import models

obs_ds
hover = models.HoverTool(tooltips=[
    ("lon", "@lon"),
    ("lat", "@lat"),
])

img.options(tools=[hover])
```
![image](https://user-images.githubusercontent.com/15331990/41071448-9b4309b8-69ac-11e8-87b2-946e1643f19a.png)

**Comment by emryslda** [comment]
Hy guys, is this issue solved?

**Comment by ahuang11** [comment]
Which part of the issue? The variable should show up correctly. However, if you project it, the lat / lon hover tooltip won't be in degrees; we're not sure on the right approach to fix that yet.

**Comment by emryslda** [comment]
That part of the issue. Without calling HoverTool but just defining tool=['hover'] inside opts i get degree. The problem is also the variable in vdims i get ??? also for the variable, any idea?
```python
xr_dataset = gv.Dataset(dataset, kdims = ['lon', 'lat','time'],vdims=['variable'])
ho=HoverTool(tooltips = [("variable", "@variable"),("(lon, lat)", "(@lon, @lat)")])
```
I tried :
```python
import matplotlib.ticker as tick
yfmt =tick.FormatStrFormatter('%2.2e')
gview_CAI=xr_dataset.to(gv.Image, ['lon', 'lat'],vdims=[hv.Dimension('variable', value_format=yfmt)])
```
but it seems to do nothing.

**Comment by ahuang11** [comment]
Still confused on what `That part of the issue` is

**Comment by emryslda** [comment]
> Still confused on what `That part of the issue` is

![g](https://user-images.githubusercontent.com/42739089/57842177-4cfa0c00-77cc-11e9-9305-bdd0d01b1e08.png)

the question marks instead of the values.

**Comment by ahuang11** [comment]
Try 
```
hover = models.HoverTool(tooltips=[
    ("lon", "xy"),
    ("lat", "@y"),
])
```

**Comment by emryslda** [comment]
> Try
> 
> ```
> hover = models.HoverTool(tooltips=[
>     ("lon", "$x"),
>     ("lat", "$y"),
> ])
> ```
> 
> but it won't be in degrees

Thank you  very much for the answer, it works but as you said not in degrees. 
1) any idea on how to show it in degrees?
2) is there any way to call the var value in vdims, i got ??? for that too?   
hview=xr_dataset.to(hv.Image, ['lon', 'lat'],vdims=[var])

**Comment by ahuang11** [comment]
You can checkout this branch to get it in degrees:
https://github.com/pyviz/holoviews/pull/3692

What is your `var` name?
if
`var = 'tmp'`

```
hover = models.HoverTool(tooltips=[
    ("lon", "$x"),
    ("lat", "$y"),
     ("tmp", "@tmp"),
])
```

**Comment by emryslda** [comment]
> You can checkout this branch to get it in degrees:
> [pyviz/holoviews#3692](https://github.com/pyviz/holoviews/pull/3692)
> 
> What is your `var` name?
> if
> `var = 'tmp'`
> 
> ```
> hover = models.HoverTool(tooltips=[
>     ("lon", "$x"),
>     ("lat", "$y"),
>      ("tmp", "@tmp"),
> ])
> ```

Still get ??? , var is a float.64 Datavariable in xarray 
var (y, x) float64 0.7663 0.7811 0.7663 0.7426 ... 0.8205 0.8103 0.7727
could be this the problem?

**Comment by ahuang11** [comment]
Sorry, it was renamed too
```
hover = models.HoverTool(tooltips=[
    ("lon", "$x"),
    ("lat", "$y"),
     ("tmp", "@image"),
])

```

**Comment by emryslda** [comment]
> hover = models.HoverTool(tooltips=[
>     ("lon", "$x"),
>     ("lat", "$y"),
>      ("tmp", "@image"),
> ])

Sorry, 

1) but what if there are more than one vdims?
2) is there any way not to show NaN values?

**Comment by ahuang11** [comment]
After the first vdim, just do `@var` where var is your second vdim's name.


```
import xarray as xr
import hvplot.xarray
from bokeh.models import HoverTool

ds = xr.tutorial.open_dataset('air_temperature').isel(time=0)

ds['airx2'] = ds['air'] * 2

import holoviews as hv
hv.extension('bokeh')

hv.Dataset(ds).to.image(['lon', 'lat'], ['air', 'airx2']).opts(tools=['hover'])

[('Longitude (degrees_east)', '$x'), ('Latitude (degrees_north)', '$y'), ('4xDaily Air temperature at sigma level 995 (degK)', '@image'), ('airx2', '@airx2')]
```

**Comment by emryslda** [comment]
@ahuang11 for me it does not work. 
I Have an RGB image object (with hv.RGB)  with values betwwen [0,1] and if i take @image I get a number of this order like: 418116853

**Comment by ahuang11** [comment]
Do the RGB values mean something (give you useful info) if you hover over it though? Maybe related to https://github.com/pyviz/hvplot/issues/204

**Comment by emryslda** [comment]
@ahuang11  No nothing useful and wrong maybe I would say. I wil give you an example of what I get so you could see what i mean.
```python
#########################################
import numpy as np
import xarray as xr
import holoviews as hv
import geoviews as gv 
import cartopy.crs as crs
from bokeh.models import HoverTool, CustomJSHover
hv.extension('bokeh','matplotlib') 
##########################################
x,y = np.mgrid[-50:51, -50:51] * 0.1
r = 0.5*np.sin(np.pi  +3*x**2+y**2)+0.5
g = 0.5*np.sin(x**2+2*y**2)+0.5
b = 0.5*np.sin(np.pi/2+x**2+y**2)+0.5
coords=np.arange(0,101)
#THIS WIL
custom=CustomJSHover(code="""
                     return value + " tot"
                     """)
tooltips=[
  ("value","@image{1.1}"),  
  ("value","@image{custom}"),
  ("G","@G"),
  ("B","@B"),
]
hover = HoverTool(tooltips=tooltips, formatters={'image' : custom})
ds = xr.Dataset({'R': (['x', 'y'],r),'G': (['x', 'y'],g),
                 'B': (['x', 'y'],b)},
                coords={'x': (['x'], coords),
                        'y': (['y'], coords)})
gv.RGB((ds['x'],ds['y'],ds.R,ds.G, ds.B),vdims=['R','G','B'], crs=crs.PlateCarree()).opts(tools=[hover])
```

**Comment by emryslda** [comment]
@ahuang11 with this example lat and lon are in degreea but for my case not well projected. Do you know how to change projection type  inside the JS code?
```python
from bokeh.models import CustomJSHover
lat_custom = CustomJSHover(code="""
    var projections = require("core/util/projections");
    var x = special_vars.x
    var y = special_vars.y
    var coords = projections.wgs84_mercator.inverse([x, y])
    return "" + coords[1]
""")
lon_custom = CustomJSHover(code="""
    var projections = require("core/util/projections");
    var x = special_vars.x
    var y = special_vars.y
    var coords = projections.wgs84_mercator.inverse([x, y])
    return "" + coords[0]
""")


hover=HoverTool(
    tooltips=[( '(lon,lat)','(@x{custom},@y{custom})' )],
    formatters=dict(x=lon_custom,y=lat_custom)
)
```

**Comment by ahuang11** [comment]
Sorry, not too sure... this JS code calls
https://github.com/bokeh/bokeh/blob/13baccbb2835f7d5831c22b5cf68214e89c02618/bokehjs/src/lib/core/util/projections.ts

**Comment by ahuang11** [comment]
@emryslda 
> I Have an RGB image object (with hv.RGB) with values betwwen [0,1] and if i take @image I get a number of this order like: 418116853 for the others (@ G,@ B) i get ???
![image](https://user-images.githubusercontent.com/15331990/61586876-66079c00-ab32-11e9-90a1-4ef579b7c62b.png)

I just encountered this and was reminded that you had the same problem. So my current workaround is also plotting a transparent hv.Image with hover cols set to R, G, B
![image](https://user-images.githubusercontent.com/15331990/61586882-8172a700-ab32-11e9-84b6-6780067a22e3.png)

**Comment by emryslda** [comment]
@ahuang11  good idea, thank you!
