### ISSUE TITLE
No plotting class for Polygons found

### ISSUE THREAD

**Issue by MatCast** [holoviz/geoviews#283]
When wanting to export a `gv.Polygons` plot to html the following error appears:
`No plotting class for Polygons found`
I am using:
```
geoviews                  1.5.1                      py_0    conda-forge
holoviews                 1.11.0                     py_0    conda-forge
```
And the following code to save the plot:
```
renderer = gv.renderer('bokeh')
g_map = gv.Polygons(gdf, vdims=['vdims], label='my_label')
renderer.save(g_map, 'map')
```

**Comment by philippjfr** [comment]
You will have to update to latest geoviews, at minimum 1.6.0 but preferably 1.6.1. Its available on the pyviz and conda-forge channels and pip.

**Comment by philippjfr** [comment]
With hv >=1.10.0 you will also be able to use the simpler hv.save function rather than going via the renderer.
