### ISSUE TITLE
VectorField does not reproject angle

### ISSUE THREAD

**Issue by poplarShift** [holoviz/geoviews#295]
Same data, two different projections (PlateCarree and NorthPolarStereo). Note how the arrows are the same, just their locations changes. The obvious fix is to reproject before calculating magnitude and angle but it might be nice to mention this in the documentation.

Cartopy on the other hand (further below) seems to do this (using `quiver`), so it might be easy to implement (then, however, using East/North velocities instead of magnitude/angle:

![platecarree](https://user-images.githubusercontent.com/38992106/52526243-b1fd0d80-2c83-11e9-943a-f5daa50ab8aa.png)

![npstereographic](https://user-images.githubusercontent.com/38992106/52526240-ac9fc300-2c83-11e9-8a95-da0ab18628d6.png)

![cartopy1](https://user-images.githubusercontent.com/38992106/52526444-c0005d80-2c86-11e9-8c6b-b49efde0def0.png)

![cartopy2](https://user-images.githubusercontent.com/38992106/52526435-9a735400-2c86-11e9-9de3-b670afe49ff1.png)

**Comment by philippjfr** [comment]
I'll consider this as a bug, this should definitely be handled.

**Comment by philippjfr** [comment]
I've had a quick go at implementing a VectorField project operation that takes into account the angle in #296. Do you think you could give that a try?

**Comment by poplarShift** [comment]
Great, I've checked it out, see my small changes.

On a slightly more general note, I must admit I am not super happy with using magnitude and angle instead of u,v for the VectorField plot. First, oceanographers/meteorologists and probably many other fields often use compass direction as angle (i.e., 0 degrees is North, 90 degrees is East), easily leading to confusion about what the angle is in a geographic context, and second, General Circulation Models usually return east/north velocity. Instruments may return angle/magnitude, but again, there are different conventions (for meteorologists, wind direction is where it is coming from, for oceanographers, current direction is where the flow goes).

**Comment by philippjfr** [comment]
>On a slightly more general note, I must admit I am not super happy with using magnitude and angle instead of u,v for the VectorField plot.

Absolutely agree with this, I think we should open an issue in HoloViews that either adds a mode to VectorField to switch between mag/angle and u/v or add an entirely separate element that accepts u,v components.

**Comment by oarcher** [comment]
>  oceanographers/meteorologists and probably many other fields often use compass direction as angle (i.e., 0 degrees is North, 90 degrees is East)

At least, it would be a good thing that vectorfield accept a keyword like `deg=True` or `deg_north=True`.
