### ISSUE TITLE
Bizarre line width rendering issue in bokeh

### ISSUE THREAD

**Issue by emryslda** [holoviz/geoviews#315]
Dear all, I am trying to use geoview to plot images, but I obtained an unwanted bold border in the image, after I gave a custom crs projection.
 the crs that I used comes from the to_crs_cartopy() function. First I defined the AreaDefinition with pyresemple.geometry.AreaDefinition , and then I transformed it with  to_crs_cartopy().
the crs output is:
_PROJ4Projection(+datum=NAD27 +ellps=WGS84 +no_defs=True +proj=utm +units=m +zone=31.0 +no_defs)

and what I got is:

https://user-images.githubusercontent.com/42739089/56588923-964ba700-65e4-11e9-887a-19081b2a7cbf.png

any idea? Thank you in advance
Here there is the code I used.

``` python
opts.defaults(
    opts.GridSpace(shared_xaxis=True, shared_yaxis=True),
    opts.Image(cmap='rainbow', width=800, height=800,projection=crs),
    opts.Labels(text_color='white', text_font_size='8pt', text_align='left', text_baseline='bottom'),
    opts.Path(color='white'),
    opts.Spread(width=600),
    opts.Overlay(show_legend=True))
gview=xr_dataset.to(gv.Image, ['x', 'y'],dynamic=True)
gview*gf.borders*gf.coastline

**Comment by djhoese** [comment]
@emryslda I think the CRS could have been created without pyresample (to ease reproducibility for the geoviews devs) by using cartopy's [UTM class](https://scitools.org.uk/cartopy/docs/v0.15/crs/projections.html#utm) with `31` specified.

**Comment by emryslda** [comment]
@djhoese Sure it is the almost same, also with it crs=crs.UTM(31)  func the problem shows up.

**Comment by philippjfr** [comment]
Sorry for not getting back to this earlier, but with current versions I cannot reproduce those line rendering issues with recent versions. Please reopen if you can still reproduce this.
