### ISSUE TITLE
geoviews.org HTTPS access

### ISSUE THREAD

**Issue by djhoese** [holoviz/geoviews#336]
The HoloViews website is accessible over HTTPS (https://holoviews.org/) but the GeoViews page is not (https://geoviews.org/). This isn't a huge deal to me, but is something I noticed today while pointing intersphinx to geoviews documentation.

**Comment by jbednar** [comment]
The same is true for https://datashader.org; I can't tell what's different about ds and gv, given that the rest of our sites work fine with https.  @jlstevens?

**Comment by philippjfr** [comment]
The difference is that these sites are hosted on AWS S3. I've been trying to fix it for geoviews, but seems I didn't quite set it up right. I have no control over datashader. The setup is pretty involved, you need to create a CDN distribution for the website, then request a certificate and add it to the DNS config.

**Comment by jbednar** [comment]
Datashader could maybe move to a different host, because the heavy-duty content has moved to examples.pyviz.org. Maybe we can save some money and also not have to fix this, for the datashader case...

**Comment by philippjfr** [comment]
The same is true for geoviews, don't think there's any real need to host that on AWS.

**Comment by philippjfr** [comment]
Let's just switch to gh-pages.

**Comment by philippjfr** [comment]
Fixed
