### ISSUE TITLE
Using GeoDataFrame.read_postgis() requires renaming geometry column

### ISSUE THREAD

**Issue by themmes** [holoviz/geoviews#349]
Not sure if this should be here or at Geopandas, please let me know if it is out of scope.

I tried to create a plot with a Geopandas dataframe created using `read_postgis()`. This function seems to look for a geometry column called `geom`. However, when I try to plot using GeoViews clearly the column should be called `geometry` in order for the plot to work. If the geometry column is called `geom` GeoViews will return the kdims error should be 2.

Temporary fix is renaming the column to geometry. However, it probably would be neater if GeoViews would look for a column using `geometry` datatype?

**Comment by philippjfr** [comment]
>Temporary fix is renaming the column to geometry. However, it probably would be neater if GeoViews would look for a column using geometry datatype?

Yes, that seems like a much cleaner solution.

**Comment by jbednar** [comment]
Note that GeoPandas has just been completely [refactored to use a Pandas ExtensionArray](https://github.com/geopandas/geopandas/pull/835) for the geometry column, so be sure to test versions of GeoPandas before and after that change if looking for a datatype rather than a column name.

**Comment by philippjfr** [comment]
>test versions of GeoPandas before and after that change if looking for a datatype rather than a column name.

Regardless it'll still be a `GeoSeries`, it's just the underlying array type that differs.
