### ISSUE TITLE
interface.select_mask error with GeoPandasInterface.length

### ISSUE THREAD

**Issue by mgsnuno** [holoviz/geoviews#378]
```python
import geopandas as gpd
import hvplot
import hvplot.pandas

world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
world.hvplot.polygons(groupby="continent")
```
fails with:
```
import geopandas as gpd...
WARNING:param.load_subset: Callable raised "ValueError('operands could not be broadcast together with shapes (10818,) (177,) (10818,) ')".
Invoked as load_subset('Oceania')
WARNING:param.dynamic_operation: Callable raised "ValueError('operands could not be broadcast together with shapes (10818,) (177,) (10818,) ')".
Invoked as dynamic_operation('Oceania')
```
This happens because of the following code, which for length calculation unpacks the (multi)polygons and calculates full number of points.
https://github.com/pyviz/geoviews/blob/668904549aec906a698babc2907cda9b11305a37/geoviews/data/geopandas.py#L184-L190

Replace it with `return len(dataset.data)` and no problems with the groupby.

The problem is then that when in `holoviews.core.data.interface.py`, `mask = np.ones(len(dataset), dtype=np.bool)` will have a different size of the groups we're grouping with.

Is `GeoPandasInterface.length` necessary to be like that? If so, how to provision for this difference, since when grouping we want the dataset length without `exploding` the polygons.

**Comment by mgsnuno** [comment]
Hi. Can anyone provide feedback on this? Thank you

**Comment by philippjfr** [comment]
I'll try to fix this very soon.

**Comment by mgsnuno** [comment]
Thanks. If I can help let me know.
