### ISSUE TITLE
gv.Bounds

### ISSUE THREAD

**Issue by ahuang11** [holoviz/geoviews#382]
I want to highlight regions with a box, but gv.Bounds doesn't exist.

**Comment by ahuang11** [comment]
I guess the alternative is making a shape

```
import geoviews as gv
from shapely.geometry import box
gv.Shape(box(*corners))
```

**Comment by philippjfr** [comment]
You can use gv.Rectangles going forward, I don't want to add non-vectorized elements at this point.
