### ISSUE TITLE
Allow to wheel zoom on a world map

### ISSUE THREAD

**Issue by fmaussion** [holoviz/geoviews#389]
#### Software version info

bokeh 1.4.0
geoviews 1.6.5
holoviews 1.12.6
datashader 0.8.0

#### Description of expected behavior and the observed behavior

Creating a map with the mwe below leads to a plot that cannot be zoomed with the wheel

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import pandas as pd
import numpy as np
import geoviews as gv
import cartopy.crs as ccrs
import datashader as ds
from holoviews.operation.datashader import rasterize
import bokeh
import holoviews as hv
hv.extension('bokeh')

data = pd.DataFrame()
data['CenLon'] = np.random.random_sample(200000) * 360 - 180
data['CenLat'] = np.random.random_sample(200000) * 180 - 90
data['area'] = np.random.random_sample(200000) * 1000
data = gv.Points(data, [('CenLon', 'Longitude'), ('CenLat', 'Latitude')], [('area', 'Area')])
data = gv.Dataset(gv.operation.project_points(data))

geo_kw    = dict(aggregator=ds.sum('area'), x_sampling=1000, y_sampling=1000)
geo_opts  = dict(dict(height=520, width=715), projection=ccrs.GOOGLE_MERCATOR)
static_geo = rasterize(gv.Points(data, crs=ccrs.PlateCarree).options(alpha=1), **geo_kw)
static_geo = static_geo.options(alpha=0.1, active_tools=['wheel_zoom'], **geo_opts) 

gv.tile_sources.ESRI * static_geo
```
I believe this must be a relatively new bug, as I think this did not affect us earlier. (the app where it doesn't work is our [glacier explorer app](http://edu.oggm.org/en/latest/explorer.html)

**Comment by philippjfr** [comment]
I think this is a twofold bug, geoviews sets the maximum map extent to be the extent of the coordinate system. The tile source adjusts that and then bokeh does not allow any zooming because you've gone past the maximum extent. We should probably disable the maximum extent setting in geoviews until bokeh allows zooming **in** when you've gone beyond it.

**Comment by fmaussion** [comment]
Thank! Is there a workaround for now?

**Comment by jbednar** [comment]
I assume you can explicitly set an extent that is the minimum of the coordinate system and the tile source's extents.

**Comment by fmaussion** [comment]
Thanks! Yes OK, the zoom in and out is actually working once one zoomed in with box zoom. But then still, the zoom out is bloked when one of the edges touches the global map borders, making it not super intuitive. But that's not a big deal, I'll just disable it for now and what for a fix upstream. Thanks for all your help!

**Comment by philippjfr** [comment]
I'll probably just push a new release today.
