### ISSUE TITLE
Enable intersphinx by hosting objects.inv

### ISSUE THREAD

**Issue by djhoese** [holoviz/geoviews#398]
**Is your feature request related to a problem? Please describe.**
I would like to link to parts of the geoviews documentation using the sphinx intersphinx extension. I'm 90% sure this used to work, but doesn't any more. The main thing is that there needs to be a `/objects.inv` hosted in the documentation. My understanding is this happens by default with normal sphinx builds:

https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html

**Describe the solution you'd like**

https://geoviews.org/objects.inv

Is it possible this file is not being included on purpose? Sphinx is still being used for documentation site generation, right?

**Comment by philippjfr** [comment]
Not including it was definitely not deliberate. We just switched over from hosting on S3 to deploying with a simpler gh-pages setup so maybe that caused the change as it doesn't add the objects.inv?

**Comment by ceball** [comment]
It might have been deliberate, but mistaken.

Here's an example of the file being removed from the geoviews website build: 
```
[...]
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 29 warnings.
The HTML pages are in ../builtdocs.
/home/travis/miniconda/envs/test-environment/bin/nbsite_fix_links.py:111: UserWarning: Found missing link ./user_guide/Gridded_Datasets_II.html in: builtdocs/user_guide/Resampling_Grids.html. 
  warnings.warn('Found missing link {} in: {}. {}'.format(a['href'], path, also_tried))
Removing files from: /home/travis/build/holoviz/geoviews/builtdocs
removing .doctrees
removing _sources
removing objects.inv
Copying json blobs (used for holomaps) from /home/travis/build/holoviz/geoviews/doc to builtdocs
cp /home/travis/build/holoviz/geoviews/doc/9a26dd393dba4610bbd10696d678d46f.json builtdocs/9a26dd393dba4610bbd10696d678d46f.json
cp /home/travis/build/holoviz/geoviews/doc/gallery/matplotlib/d36be3bff5dc4661acf267f72f89a1bd.json builtdocs/gallery/matplotlib/d36be3bff5dc4661acf267f72f89a1bd.json
[...]
```
(https://travis-ci.org/holoviz/geoviews/jobs/617439369#L2234)

I've opened https://github.com/pyviz-dev/nbsite/issues/153

**Comment by djhoese** [comment]
Now that the `nbsite` repository issue is fixed/closed, what needs to happen for geoviews' docs to be rebuilt?

**Comment by ceball** [comment]
Should be: (1) release a new version of nbsite, and then (2) re-build the geoviews website.

(1) Should just be pushing a release tag for nbsite (and writing release notes), then new packages will appear. I've started that process.

(2) Might be as easy as pushing a website build tag to geoviews, but I haven't done that for ages (if ever). It also maybe depends how close to a new release geoviews is. (We don't have versioned docs yet, so the website probably shouldn't be too far from the last release...)

**Comment by ceball** [comment]
The nbsite 0.6.6 packages appeared.

**Comment by philippjfr** [comment]
Finally fixed, sorry for the delay.
