### ISSUE TITLE
issues with TileServers

### ISSUE THREAD

**Issue by eliavst** [holoviz/geoviews#404]
Using Bokeh 1.3.4 and GeoViews 1.6.6

Two issues that seem to be related:

1) When trying to loas OSM tile source, I get an empty map although "OpenStreetMap Contributers" appears on bottom right. Tried loading from WMTS link and same error occurs. When
I zoom out or try to move map, map gets completely distorted (works fine with zooming in).
```
import geoviews as gv
import geoviews.tile_sources as gts
gv.extension("bokeh")
tiles = gts.OSM
tiles 
```
![OSM error](https://user-images.githubusercontent.com/41321738/70387375-4d970180-19ad-11ea-9029-358b1214486a.gif)

2) When I load local tileserver that was created in QGIS, it load fine and I am able to zoom in, but same as OSM once I move map or zoomout it becomes completely distorted.
```
import geoviews as gv
from bokeh.models import WMTSTileSource
gv.extension("bokeh")
tiles = gv.WMTS(WMTSTileSource(url='http://localhost/tileserver/wt3/{Z}/{X}/{Y}.png'))
tiles
```
![localtile error](https://user-images.githubusercontent.com/41321738/70387390-75866500-19ad-11ea-94f6-c4819ec2da16.gif)

**Comment by philippjfr** [comment]
Does this issue persist with bokeh 1.4.0? I would expect it does but just wanted to rule things out. Your browser version may also be helpful.

**Comment by jbednar** [comment]
I've seen the "distorted" behavior for many months or years (on various Mac OS X Chrome versions), but I've never captured a reproducible example.

**Comment by philippjfr** [comment]
Personally I haven't seen the issue in over a year.

**Comment by jbednar** [comment]
It's been about a month or two for me. But my workloads vary, so I haven't assumed that the problem has gone away, just that I haven't been hitting it.

**Comment by eliavst** [comment]
So apparently it was the browser I was using (Firefox - 67.0.4) that was causing the OSM issue. With Chrome (78.0.3904.108 (Official Build) (32-bit)) it's working fine. 

The local tileserver issue remains unsolved on both browsers. 

I'm trying to update to Bokeh 1,4.0, but getting some inconsistencies:
>The following packages are causing the inconsistency:
> - defaults/win-64::cartopy==0.17.0=py37h5ae9855_1
> - defaults/noarch::geopandas==0.6.1=py_0
>- pyviz/noarch::geoviews==1.6.6=py_0
>  - pyviz/noarch::geoviews-core==1.6.6=py_0
> - defaults/noarch::owslib==0.18.0=py_0

Will update once I manage to get through with the update

**Comment by eliavst** [comment]
So seems like Bokeh 1.4.0 solved the problem. Should have tried that first, sorry for hassle.
