### ISSUE TITLE
Pinning proj4

### ISSUE THREAD

**Issue by philippjfr** [holoviz/geoviews#417]
While cartopy now has nominal support for proj6 (see https://github.com/SciTools/cartopy/pull/1289) the doc build fails miserable using that configurations. Specifically projecting from RotatedPole coordinates fails, and at least on travis it seems like we are getting this error in many cases:

```
proj_create_from database: Cannot find proj.db
```

which happens because the PROJ_LIB environment variable isn't being set. To ensure optimal (or rather predictable) behavior for both our users and our builds I'd like to pin proj4 for the time being and monitor the situation in cartopy, e.g. their test suite also currently does not pass with proj6 installed.

**Comment by ppwadhwa** [comment]
This may not be specifically proj4 related, but pinning in general will need to be revisited in order to fix issue #446.

**Comment by philippjfr** [comment]
I've now unpinned.
