### ISSUE TITLE
Drawing tool dragging broken

### ISSUE THREAD

**Issue by jbednar** [holoviz/geoviews#428]
For the latest master versions and released Bokeh:

holoviews=1.13.0a21.post4+ga511f2290
geoviews=1.7.0a6.post2+g5df9239
panel=0.7.1a2.post16+g446e572
bokeh=1.4.0                    

the following code doesn't let the points be dragged, but does work if the gv.Points line is commented out and the hv.Points line is used instead:

```
import holoviews as hv, geoviews as gv
hv.extension('bokeh')
pts = ([36.5,36.6,36.7], [-121.9, -121.7, -121.8])

#points = hv.Points(pts)
points = gv.Points(dict(Latitude=pts[0], Longitude=pts[1]))
hv.annotate(points.opts(size=10))
```

Something to do with the custom models used in GeoViews?  Note that _importing_ geoviews was not sufficient to cause a problem; it's when actually using the gv.Points object.

**Comment by philippjfr** [comment]
This is a tool activation issue which was resolved with bokeh 2.0.
