### ISSUE TITLE
PIL dependency: Incompatible library version: libtiff.5.dylib

### ISSUE THREAD

**Issue by digitaltopo** [holoviz/geoviews#438]
#### ALL software version info
Python 3.7
macOS Sierra 10.12.06
Anaconda 3

#### Description of expected behavior and the observed behavior
Expected successful import of geoviews package.
Observed: Import geoviews fails due to issue with PIL

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import geoviews
```

#### Stack traceback and/or browser JavaScript console output
```python
ImportError: dlopen(/opt/anaconda3/envs/myenv/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libwebp.7.dylib
  Referenced from: /opt/anaconda3/envs/myenv/lib/libtiff.5.dylib
  Reason: Incompatible library version: libtiff.5.dylib requires version 9.0.0 or later, but libwebp.7.dylib provides version 8.0.0
```

**Comment by philippjfr** [comment]
Thanks for filing the issue but this is not an issue with GeoViews but rather with your installation of PIL. Please refer to [Stackoverflow](https://stackoverflow.com/questions/22728468/osx-pillow-incompatible-library-version-libtiff-5-dylib-libjpeg-8-dylib) or the [conda-forge repo](https://github.com/conda-forge/libtiff-feedstock/issues/53)
