### ISSUE TITLE
Disable bokeh plot axis scrolling for geo plots

### ISSUE THREAD

**Issue by digitaltopo** [holoviz/geoviews#445]
#### Is your feature request related to a problem? Please describe.
Geo plots allow for axis scrolling, this should be disabled by default, since it's the expected user experience to not stretch a map axis.
By request from @philippjfr  https://discourse.holoviz.org/t/disable-bokeh-plot-axis-scrolling/285/4?u=digitaltopo

#### Describe the solution you'd like
Make geo plots disable plot axis scrolling by default.

#### Describe alternatives you've considered
I was able to achieve this functionality by creating a custom instance of the WheelZoomTool:
```python
import geoviews.feature as gvfs
import holoviews as hv
from bokeh.models import WheelZoomTool

wheel_zoom = WheelZoomTool(zoom_on_axis=False)
gvts.OSM().opts(default_tools=['pan', wheel_zoom],)
```

#### Additional context
https://discourse.holoviz.org/t/disable-bokeh-plot-axis-scrolling/285

**Comment by philippjfr** [comment]
I'm a bit confused this should already be the case, in fact when I try it is already disabled.

**Comment by digitaltopo** [comment]
I guess this got added at some point recently.

**Comment by philippjfr** [comment]
Still confused really, it got added two years ago but I swear I did see this behavior more recently too 🤷‍♂

**Comment by digitaltopo** [comment]
There may have be some combination of plots that re-enable this? I had to
manually disable it recently using the technique above but have also
noticed it seems like it is usually disabled by default in other cases.

**Comment by philippjfr** [comment]
Possible that a layout would reenable this when the tools are merged.
