### ISSUE TITLE
error in importing geoviews..what maybe the problem

### ISSUE THREAD

**Issue by Qooley** [holoviz/geoviews#459]
In [1]: import geoviews                                                         
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-bb2ce275a55a> in <module>
----> 1 import geoviews

~/anaconda3/envs/pykip/lib/python3.8/site-packages/geoviews/__init__.py in <module>
     11     pass
     12 #%%
---> 13 from .annotators import annotate # noqa (API import)
     14 from .element import ( # noqa (API import)
     15     _Element, Feature, Tiles, WMTS, LineContours, FilledContours,

~/anaconda3/envs/pykip/lib/python3.8/site-packages/geoviews/annotators.py in <module>
      1 import param
      2 
----> 3 import cartopy.crs as ccrs
      4 
      5 from holoviews.annotators import (

~/anaconda3/envs/pykip/lib/python3.8/site-packages/cartopy/__init__.py in <module>
     94 # Commonly used sub-modules. Imported here to provide end-user
     95 # convenience.
---> 96 import cartopy.crs
     97 import cartopy.feature  # noqa: F401  (flake8 = unused import)

~/anaconda3/envs/pykip/lib/python3.8/site-packages/cartopy/crs.py in <module>
     34 import six
     35 
---> 36 from cartopy._crs import (CRS, Geodetic, Globe, PROJ4_VERSION,
     37                           WGS84_SEMIMAJOR_AXIS, WGS84_SEMIMINOR_AXIS)
     38 from cartopy._crs import Geocentric  # noqa: F401 (flake8 = unused import)

ImportError: libproj.so.19: cannot open shared object file: No such file or directory

**Comment by suvarchal** [comment]
Quoting from the docs: https://geoviews.org
> In certain circumstances proj6 issues may prevent installation or cause issues (particularly with cartopy<=0.17). If you encounter these issues ensure you also pin proj4:
> 
> conda install proj4<6
> 

would that help?

**Comment by ppwadhwa** [comment]
Closing as this seems to be an upstream issue with cartopy.
