### ISSUE TITLE
recent update to geoviews-1.6.6 will not load

### ISSUE THREAD

**Issue by ebo** [holoviz/geoviews#460]
I just updated my dev system, and now every time I import geoviews I get the following error:

> The kernel appears to have died. It will restart automatically.

When I added %debug to see if it would generate any usful information as to why, I get the following:

> ERROR:root:No traceback has been produced, nothing to debug.

any suggestions?

**Comment by ppwadhwa** [comment]
This is usually an issue with one of geoviews' dependencies, which commonly is gdal or shapely.  Try importing shapely and if that crashes, file an issue on the shapely issue tracker.

Closing for now, but can re-open if you have more details to provide and this does seem related to geoviews.
