### ISSUE TITLE
Incorrect representation of Crimea

### ISSUE THREAD

**Issue by NikYUR** [holoviz/geoviews#461]
Dear Sirs,

I'm learning your great library documentation.

I have noted that library shows Crimea as part of russian territory.

This is incorrect. Crimea is an Ukrainian part and temporary occupied by Russian Federation.

For this most of countries in the world have sanctioned Russia.

Please correct this issue.

With great respect and thank.
Nik

**Comment by jbednar** [comment]
Thanks for the feedback! However, GeoViews does not include any border information itself; it only makes data available that is imported from other sources. Here I would guess that you're referring to geoviews.feature.borders, which comes from [Cartopy](https://scitools.org.uk/cartopy), and so please raise the issue there in that case.
