### ISSUE TITLE
Check for active geometry column in GeoDataFrame

### ISSUE THREAD

**Issue by martinfleis** [holoviz/geoviews#474]
#### Is your feature request related to a problem? Please describe.
When plotting Geopandas GeoDataFrame using `gv.Polygons(gdf)`, geoviews does not use the active geometry column set in gdf but defaults to a column called geometry. 

#### Describe the solution you'd like
In the ideal case, the set geometry column should be used.

#### Describe alternatives you've considered
Now you have to make sure that your geometry you want to plot is in `"geometry"` column.

#### Additional context
```python
import pandas as pd
import geopandas as gpd

df = pd.DataFrame([[51.502687, -3.538329, 2242, 1, 47],
                   [52.699185, -0.050122, 870, 2, 35],
                   [51.574387, 0.397882, 651, 3, 47],
                   [51.43874, 0.395791, 625, 4, 35],
                   [51.23965, 0.561919, 614, 5, 36]],
                   columns = ["lat","long","num_of_trucks","performance","num_of_routes"]
                 )

gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df["lat"],df["long"]),
                                                                 crs="epsg:4326")

gdf["buffer_radius"] = gdf.geometry.buffer(1)
gdf = gdf.set_geometry('buffer_radius')

gv.Polygons(gdf)
```
This comes out empty.

**Comment by martinfleis** [comment]
I think that changing this to a code below will do the trick:

https://github.com/holoviz/geoviews/blob/e569e23ff72c36e3493f5ccfcdc314bad0b05887/geoviews/data/geopandas.py#L42-L51

```python
def geo_column(cls, data): 
    from geopandas import GeoDataFrame, GeoSeries
    
    if isinstance(data, GeoDataFrame) and hasattr(gdf, 'geometry'):
        return data.geometry
    cols = [c for c in data.columns if isinstance(data[c], GeoSeries)] 
    if not cols and len(data): 
        raise ValueError('No geometry column found in geopandas.DataFrame, ' 
                      'use the PandasInterface instead.') 
    return cols[0] if cols else None

```

I would personally remove the check for other GeoSeries than active geometry, but that is entirely up to you.

**Comment by jbednar** [comment]
From your first comment I thought you were saying that a column must be named "geometry" for it to be recognized currently, which doesn't seem to be true from the code.  But re-reading your comment I _think_ what you are saying is that currently a column named "geometry" is taken as the active geometry column even if another column was so indicated using `set_geometry`, and you're requesting that we respect the call to `set_geometry` rather than the name "geometry". If so, I think I agree.

**Comment by martinfleis** [comment]
> currently a column named "geometry" is taken as the active geometry column even if another column was so indicated using set_geometry, and you're requesting that we respect the call to set_geometry rather than the name "geometry"

Yes, sorry if it was not clear.
