### ISSUE TITLE
Value for __version__ doesn't match installed version

### ISSUE THREAD

**Issue by stefmolin** [holoviz/geoviews#521]
#### ALL software version info
    - python=3.8.11
    - bokeh=2.3.3
    - jupyterlab=3.1.1
    - matplotlib=3.4.3
    - numpy=1.21.2
    - pandas=1.3.2
    - seaborn=0.11.2
    - geoviews=1.9.1
    - holoviews=1.14.5
    - setuptools=57.4.0

#### Description of expected behavior and the observed behavior

When accessing the `__version__` member, I expect it to contain the installed version (1.9.1). However, it is returning '0.0.0+g33876c88-gitarchive' instead. Running `conda list geoviews` confirms that 1.9.1 is the installed version.

#### Complete, minimal, self-contained example code that reproduces the issue

```
>>> import geoviews
>>> print(geoviews.__version__)
'0.0.0+g33876c88-gitarchive'
```

**Comment by philippjfr** [comment]
Thanks for reporting this, looking into it now!

**Comment by philippjfr** [comment]
Assume you got the release from conda-forge? That was erroneously pointing to the GH archive tarball which is not a supported configuration. I'll release a new build which uses the PyPI release as the source.

**Comment by stefmolin** [comment]
Actually, I was able to solve it by explicitly installing geoviews-core from pyviz and then geoviews from pyviz. Geoviews was coming from pyviz, but geoviews-core was then being installed from conda-forge.

**Comment by philippjfr** [comment]
Glad you found a solution, and thanks for reporting it!

**Comment by stefmolin** [comment]
No problem! I'm happy to test with my old setup when the new build is ready if you like.

**Comment by philippjfr** [comment]
That would be hugely appreciated, the new 1.9.1 should now be available on conda-forge.

**Comment by stefmolin** [comment]
Confirming that the new build fixed the issue.

**Comment by philippjfr** [comment]
Thanks again.
