### ISSUE TITLE
Geoviews not plotting higher-res Cartopy features?

### ISSUE THREAD

**Issue by bruxerjk** [holoviz/geoviews#527]
First time reporting what I think is a bug, apologies if it's not and if I'm overlooking something.  

I can't seem to properly access higher-resolution (e.g., 10m) Natural Earth features through Geoviews.  I've tried to rule out the possibility that Cartopy is the problem below.

I'm using the following in my conda environment:
matplotlib = 3.4.2
cartopy = 0.20.0
holoviews = 1.14.5
geoviews = 1.9.1

This self-contained example code runs fine in a jupyter notebook and plots the high (10m) resolution features `LAND`, `COASTLINE`, and  `lakes_hr`:
```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cf

lakes_hr = cf.NaturalEarthFeature(
        category='cultural',
        name='admin_0_countries_lakes',
        scale='10m',
        edgecolor='black',
        facecolor='none')

ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([-95, -62, 40, 55])
ax.add_feature(cf.LAND)
ax.add_feature(cf.COASTLINE)
ax.add_feature(lakes_hr)

plt.show()
```

![image](https://user-images.githubusercontent.com/46026810/134776071-75fcb044-0287-4973-8207-4c2aa8127283.png)

This is also self-contained, again in a jupyter notebook it runs through completion without errors and should display a similar graphic to that above.  However, instead of the high-resolution features, it resorts to lower-resolution versions of `land`, `coastline` and `lakes_hr`:

```
import cartopy.feature as cf
import geoviews.feature as gf
from geoviews import opts

import holoviews as hv
hv.extension('matplotlib')

lakes_hr = cfeature.NaturalEarthFeature(
        category='cultural',
        name='admin_0_countries_lakes',
        scale='10m',
        edgecolor='black',
        facecolor='none')

fig = gf.land * gf.coastline * gf.Feature(lakes_hr)
fig.opts(xlim=(-95, -62), ylim=(40, 55), fig_size=400)
fig
```
![image](https://user-images.githubusercontent.com/46026810/134777406-4c9949fe-4d6d-4ba8-acd6-72660d307b6c.png)

**Comment by ahuang11** [comment]
I think you can do
.opts(scale="10m")

or `.with_scale('10m')`
