### ISSUE TITLE
geoviews get_extents really slow with cartopy=0.20

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/geoviews#529]
cartopy is now using pyproj, but it's causing major performance issues in my app. I will try to create a minimal example soon.
![image](https://user-images.githubusercontent.com/83971150/135644299-de0d7476-a632-471a-b219-3e757af07a61.png)

**Comment by andhuang-CLGX** [comment]
https://github.com/SciTools/cartopy/issues/1895

**Comment by andhuang-CLGX** [comment]
Takes 24 seconds to create the image
```
import datetime
import geoviews as gv
import cartopy.crs as ccrs
gv.extension("bokeh")

s = datetime.datetime.utcnow()
display(gv.tile_sources.CartoDark() * gv.Points(([-88, -95, -100], [40, 50, 60]), crs=ccrs.PlateCarree()))
e = datetime.datetime.utcnow()
print(e - s)
```

**Comment by andhuang-CLGX** [comment]
Downgraded to cartopy==0.19.0
And it finished in: `0:00:00.183278`

**Comment by dcherian** [comment]
downgrading to cartopy==0.19.0 worked for me too. Thanks @andhuang-CLGX

**Comment by andhuang-CLGX** [comment]
Thoughts on path forward to fix this? Wait for cartopy to introduce a cache or implement a local change to geoviews like: https://github.com/SciTools/cartopy/issues/1895#issuecomment-932321937

**Comment by philippjfr** [comment]
Expect we can be quicker, so let's go ahead and implement this ourself.

**Comment by maximlt** [comment]
I've posted a comment on the issue opened on Cartopy's issue tracker (https://github.com/SciTools/cartopy/issues/1895#issuecomment-982982168). It shows that equality test has become more than significantly slower, and we've got a few of them in `holoviews/plotting/plot/get_extents` and `holoviews/plotting/plot/_get_range_extents`. There may still me a way to implement a cache at the geoviews level.

**Comment by maximlt** [comment]
Replacing each occurrence of `self.projection == '3d'` in holoviews by `isinstance(self.projection, str) and self.projection == '3d'` fixes the issue.  @philippjfr what do you think about that?

**Comment by philippjfr** [comment]
That seems reasonable but it might be nice to upstream that short-circuit in the equality check inside cartopy.

**Comment by maximlt** [comment]
Fixed by https://github.com/holoviz/holoviews/pull/5152

For users who might encounter this issue in the future, the solution is either to update holoviews to a version greater or equal than `1.14.7` (to be released soon) or to downgrade cartopy to a version less than `0.20`.

**Comment by maximlt** [comment]
> That seems reasonable but it might be nice to upstream that short-circuit in the equality check inside cartopy.

`string` objects can be valid PROJ projections so I don't think there's a way for cartopy to short-circuit that unfortunately.
