### ISSUE TITLE
Show image value generated by shade

### ISSUE THREAD

**Issue by zxdawn** [holoviz/geoviews#535]
As suggested by @kidpixo in another [issue](https://github.com/Quansight/lsst_dashboard/issues/43#issuecomment-575196375), we can rasterize once, and then shade it to make the colorbar work with datashade.

However, if I add the hover tool, the image value is `RGBA`, even if I set it to `@image` manually.
Note that if I set `('Tair_test', '@Tair')`, the value is `????`

![image](https://user-images.githubusercontent.com/30388627/139678271-22284953-1033-44eb-a069-fba6a4387aee.png)

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

geoviews: 1.9.2
bokeh: 2.4.1

#### Description of expected behavior and the observed behavior

Hover shows the image value instead of RGBA.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import xarray as xr
import geoviews as gv
from geoviews import opts
import cartopy.crs as ccrs
import geoviews.feature as gf
from bokeh.models import HoverTool
from holoviews.operation.datashader import datashade, rasterize, shade

gv.extension("bokeh")

# Some arbitrary sizes we will use to display images.
image_height, image_width = 600, 600

# Maps will have the same height, but they will be wider
map_height, map_width = image_height, 1000

colormap_to_use = 'Spectral_r'

# set default opts
opts.defaults(
  opts.QuadMesh(cmap=colormap_to_use, 
                height=image_height, width=image_width, 
                colorbar=True, 
                tools=['hover'], active_tools=['wheel_zoom'], 
),
  opts.Feature(active_tools=['wheel_zoom'], height=map_height, width=map_width)
)

# read data
ds = xr.tutorial.open_dataset('rasm').load()

gvds = gv.Dataset(ds.where(ds['yc']>=60, drop=True).isel(time=0),
                 crs=ccrs.PlateCarree(),
                 )

mesh = gvds.to(gv.QuadMesh, kdims=["xc", "yc"], vdims=['Tair'])

# set hover
tooltips = [
    ('Longitude', '$x'),
    ('Latitude', '$y'),
    ('Tair', '@image'),
]

hover = HoverTool(tooltips=tooltips)

raster = rasterize(gv.project(mesh, projection=ccrs.NorthPolarStereo())).opts(alpha=1, cmap=colormap_to_use, colorbar=True)

raster*\
shade(raster, cmap=colormap_to_use).opts(projection=ccrs.NorthPolarStereo(), 
                       height=image_height, width=image_width, 
                       tools=[hover], active_tools=['wheel_zoom']
                      )
```

**Comment by zxdawn** [comment]
### More info

The default hover applied to `rasterize` works well:
```
rasterize(gv.project(mesh, projection=ccrs.NorthPolarStereo()))\
.opts(alpha=1, cmap=colormap_to_use, tools=['hover'], colorbar=True, height=image_height, width=image_width)
```

![image](https://user-images.githubusercontent.com/30388627/139689376-1a08db6d-63cb-4957-afdd-df48d102eee9.png)

Overlaying the shade doesn't work:
```
raster = rasterize(gv.project(mesh, projection=ccrs.NorthPolarStereo()))\
.opts(alpha=1, cmap=colormap_to_use, tools=['hover'], colorbar=True, height=image_height, width=image_width)

raster*\
shade(raster, cmap=colormap_to_use).opts(projection=ccrs.NorthPolarStereo(), 
                       height=image_height, width=image_width, 
                       tools=['hover'], active_tools=['wheel_zoom']
                      )
```
![image](https://user-images.githubusercontent.com/30388627/139689627-41e82f10-0409-4db1-8d9f-5e9a5cd5c99d.png)

**Comment by jbednar** [comment]
I may be confused, but I can't see why `shade` would be needed here. Wouldn't `rasterize` alone be sufficient, which would make hover work properly without any extra work?

**Comment by zxdawn** [comment]
Ha, yes. I made it more complicated ... Thanks for the remind!
