### ISSUE TITLE
gv.Path does not work at all. hv.Path works

### ISSUE THREAD

**Issue by RichardPinter** [holoviz/geoviews#551]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
import pyproj
import geoviews as gv
import geoviews.feature as gf
from geoviews import dim
from geoviews import opts
from geoviews.element import WMTS
import geoviews.tile_sources as gts
import cartopy.crs as ccrs
gv.extension('bokeh', 'matplotlib')
import pandas as pd
import cartopy.feature as cf
from cartopy import crs
import holoviews as hv

#### Description of expected behavior and the observed behavior

Geoviews does not work with the following code. On the other hand if I change gv. to hv. it works.  Does anyone have information why this is happening?

#### Complete, minimal, self-contained example code that reproduces the issue

```
llist = ([16560393, 16570394 , 16580392 ]),([-2618357, -2617356, -2616358])
llist= list(zip(path_df.Longitude, path_df.Latitude))
P= gv.Path(data = llist)
# P = gv.operation.project(P, projection=crs.GOOGLE_MERCATOR)
M = P*map_to_use
M.opts(xlim=(XMIN,XMAX),ylim =(YMIN,YMAX), height=400, width=800)   
gv.save(M,"p.html")
```

#### Screenshots or screencasts of the bug in action

Hv.Path version very clearly there is a Path
![Screenshot from 2022-01-16 19-25-32](https://user-images.githubusercontent.com/38550474/149653610-6f321658-3387-4391-94c0-d3a26e2c7b58.png)

On the other hand gv.Path does not display anything
![Screenshot from 2022-01-16 19-25-58](https://user-images.githubusercontent.com/38550474/149653615-51b476a3-e4a8-4d80-8f3f-1dbea909f0fa.png)

**Comment by jbednar** [comment]
It's hard to be sure without a runnable example, but I'd assume this is to do with projections, trying to overlay lat/lon values as Web Mercator or vice versa. If it works in hv and not gv, my guess is that your values are in Web Mercator but GeoViews is being told (or assumes) that they are in lat/lon, so either feed lat/lon values to GeoViews or else tell GeoViews the correct projection that matches the data (e.g. `gv.Path(..., crs=crs.GOOGLE_MERCATOR`).

**Comment by RichardPinter** [comment]
Thanks for the reply!

Here is a code chunk that you can run 


Libraries I use:


#####################
## Read in libraries
import pyproj
import geoviews as gv
import geoviews.feature as gf
from geoviews import dim
from geoviews import opts
from geoviews.element import WMTS
import geoviews.tile_sources as gts
import cartopy.crs as ccrs
gv.extension('bokeh', 'matplotlib')
import pandas as pd
import cartopy.feature as cf
from cartopy import crs
import holoviews as hv

#####################


Code snippet that works just below, using hv.Path(),  and a code snippet that does not work, using gv.Path(),  is at the bottom.

######################

tiles =gv.tile_sources.Wikipedia()
llist = ([16560393, 16570394 , 16580392 ]),([-2618357, -2617356, -2616358])
P= hv.Path(data = llist)
M = P*tiles
gv.save(M,"p.html")

######################

And the following code outputs this;
![Screenshot from 2022-01-20 09-28-01](https://user-images.githubusercontent.com/38550474/150231943-161893d0-ffe8-4646-aebb-285266bb823c.png)


If I run this 


######################

tiles =gv.tile_sources.Wikipedia()
llist = ([16560393, 16570394 , 16580392 ]),([-2618357, -2617356, -2616358])
P= gv.Path(data = list,crs=crs.GOOGLE_MERCATOR )
M = P*tiles
gv.save(M,"p.html")

######################

I'll get this:
![Screenshot from 2022-01-20 09-28-31](https://user-images.githubusercontent.com/38550474/150231985-b494dde2-fb4f-41a1-bda6-64e3c72d9875.png)


Thank you for your help in advance. I hope you can run the code now

**Comment by philippjfr** [comment]
You had a typo in your code, in the gv version you set `data=list` when you meant `data=llist`. If you fix that it works fine:

```python
tiles =gv.tile_sources.Wikipedia()
llist = ([16560393, 16570394 , 16580392 ]),([-2618357, -2617356, -2616358])
P= gv.Path(data = llist,crs=crs.GOOGLE_MERCATOR )
M = P*tiles
```

<img width="310" alt="Screen Shot 2022-02-17 at 12 00 52" src="https://user-images.githubusercontent.com/1550771/154467058-9b3246a7-6a00-4f8d-b051-99f9cfcc7a40.png">
