### ISSUE TITLE
Locations in hvplot raises warning

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/geoviews#576]
#### ALL software version info
``` yaml
geoviews   : 1.9.5
holoviews  : 1.15.0a2
hvplot     : 0.8.0
```

#### Description of expected behavior and the observed behavior
When having features like `coastline` called by `hvplot` a warning is given with the latest dev release of `holoviews`. The warning is not present with version 1.14.

I have added the bug in Geoviews as this is where the warning is emitted from:
 
https://github.com/holoviz/geoviews/blob/1bd771233dfbd1208e86224f987c9003f121164a/geoviews/element/geo.py#L149-L150

#### Complete, minimal, self-contained example code that reproduces the issue

``` python
import xarray as xr
import hvplot.xarray

data = xr.tutorial.open_dataset("rasm").load()['Tair'].isel(time=0)
data.hvplot.quadmesh('xc', 'yc', coastline=True)

```

#### Screenshots or screencasts of the bug in action
With `holoviews` 1.15:
![image](https://user-images.githubusercontent.com/19758978/174778609-71e3bc41-8921-4df6-8ca5-73d55d9b9ae1.png)

With `holoviews` 1.14:
![image](https://user-images.githubusercontent.com/19758978/174777942-5729a4e4-b138-4b78-ac42-465acc30c179.png)

**Comment by philippjfr** [comment]
Thanks @Hoxbro!

**Comment by Hoxbro** [comment]
Fixed downstream by https://github.com/holoviz/hvplot/pull/850
