### ISSUE TITLE
ShapelyDeprecationWarning

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/geoviews#589]
When I run the hvPlot Geographic_Data.ipynb notebook using geoviews 1.9.5, I see

```bash
/opt/conda/lib/python3.9/site-packages/geoviews/operation/projection.py:79: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  polys = [g for g in geom if g.area > 1e-15]
```

![image](https://user-images.githubusercontent.com/42288570/187059325-2cdc0418-2e48-4a4b-aa1e-74e79eeee740.png)

![image](https://user-images.githubusercontent.com/42288570/187059381-8bb157ed-de98-4cfe-8409-e41087074a27.png)

**Comment by Hoxbro** [comment]
This is fixed on master with https://github.com/holoviz/geoviews/pull/570. 

![image](https://user-images.githubusercontent.com/19758978/187060881-ca0c6835-e24a-43a9-9d6d-5ee41aaeed6d.png)

But it is annoying, so a new release (patch?) release could be made to fix it.
