### ISSUE TITLE
Make `pyproj` a runtime dependency

### ISSUE THREAD

**Issue by maximlt** [holoviz/geoviews#621]
https://github.com/holoviz/geoviews/pull/583 added a direct import from `pyproj`, while before the code was using it only when it was already imported (looking into`sys.modules`). Since cartopy [depends](https://github.com/SciTools/cartopy/blob/main/requirements/default.txt) on pyproj, and GeoViews depends on cartopy, it seems fine to add `pyproj` as a runtime dependency to GeoViews.

**Comment by Hoxbro** [comment]
It was not a deliberate decision to add it as a runtime dependency on my part.

But I agree with adding it as a runtime dependency.
