### ISSUE TITLE
ImportError calling geoviews

### ISSUE THREAD

**Issue by gsapriza** [holoviz/geoviews#646]
After installing geoviews 

#### geoviews version and some dependecies
# Name                    Version                   Build  Channel
geoviews                  1.8.2                      py_0    pyviz
geoviews-core           1.8.2                      py_0    conda-forge
# Name                    Version                   Build  Channel
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
# Name                    Version                   Build  Channel
cartopy                   0.17.0          py38hde43876_1009    conda-forge
# Name                    Version                   Build  Channel
holoviews                 1.16.0                     py_0    pyviz

#### 
When I try to init the module, the following error appear:
import geoviews
Traceback (most recent call last):

  File "C:\Users\saprizag\AppData\Local\Temp/ipykernel_15084/1166259778.py", line 1, in <module>
    import geoviews

  File "C:\Users\saprizag\Anaconda3\envs\spyder-env\lib\site-packages\geoviews\__init__.py", line 13, in <module>
    from .annotators import annotate # noqa (API import)

  File "C:\Users\saprizag\Anaconda3\envs\spyder-env\lib\site-packages\geoviews\annotators.py", line 14, in <module>
    from .links import VertexTableLink, PointTableLink, HvRectanglesTableLink, RectanglesTableLink

  File "C:\Users\saprizag\Anaconda3\envs\spyder-env\lib\site-packages\geoviews\links.py", line 4, in <module>
    from holoviews.plotting.bokeh.callbacks import (

ImportError: cannot import name 'LinkCallback' from 'holoviews.plotting.bokeh.callbacks' (C:\Users\saprizag\Anaconda3\envs\spyder-env\lib\site-packages\holoviews\plotting\bokeh\callbacks.py)

Any help will be usefull

Thanks

**Comment by Hoxbro** [comment]
Try updating to `Bokeh=3.1.1` and `Geoviews=1.10.0`, preferably from a clean environment.

**Comment by gsapriza** [comment]
Thanks. Works fine

**Comment by philippjfr** [comment]
Thanks for reporting back @gsapriza!
