### ISSUE TITLE
Coastline + Rasterize shows blank plot

### ISSUE THREAD

**Issue by ahuang11** [holoviz/geoviews#726]
Still an issue from https://github.com/holoviz/geoviews/pull/722
```python
import xarray as xr
import panel as pn
import holoviews as hv
from holoviews.operation.datashader import rasterize
import geoviews as gv
import cartopy.crs as ccrs

hv.extension("bokeh")
import hvplot.xarray
ds = xr.tutorial.open_dataset("air_temperature").isel(time=0)

rasterize(gv.Image(ds, ["lon", "lat"], ["air"])) * gv.feature.coastline()
```

**Comment by TheoMathurin** [comment]
It's odd, in my experience the issue manifested itself when there was a datashader operation involved on both elements (image and geometry), as reported in #593.

**Comment by ahuang11** [comment]
Finally figured out what is causing this issue, but not sure why. It was introduced in https://github.com/holoviz/geoviews/pull/722

Commenting out https://github.com/holoviz/geoviews/pull/722/files#diff-170766bf0fca811f003fd9c97058f978c51b672af33a49cceab87d3584de2cf5R126-R129 makes it work again

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/d30d30c4-dbbc-4bc8-be3d-05f031ddba50">

With that snippet though, rasterize(obj) * coastline returns empty image

<img width="1415" alt="image" src="https://github.com/user-attachments/assets/4010492a-1865-41fb-a0fb-f78417f1abc0">

Even if I ONLY keep without the unwrap clause, it'd still return an empty image with an overlay
```python
    def update_frame(self, key, ranges=None, element=None):
        super().update_frame(key, ranges, element)

```

Any ideas @hoxbro or @philippjfr?

**Comment by ahuang11** [comment]
Heh asking for help always helps me figure it out faster :D

I guess the lesson is always follow best practices; optional kwargs should always have `key=value`. The positional args didn't match the keyword arguments.

<img width="424" alt="image" src="https://github.com/user-attachments/assets/e5c1e356-88f0-44f7-bf05-48a706a2fc79">
