### ISSUE TITLE
Regression: RangeXY now provides incorrect longitude x_range

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/geoviews#753]
#### ALL software version info
I think only hv and gv versions are relevant
```plaintext
geoviews 1.13.0
holoviews 1.19.1
```
</details>

#### Description of expected behavior and the observed behavior
Potentially a serious regression that breaks a lot of things in my apps.

Assuming a Plate Carree crs, longitudes returned by `hv.streams.RangeXY` were always given between -180 et 180.

They are now given in the (0, 360) interval when they are both in the western hemisphere.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn
import holoviews as hv
import geoviews as gv


def print_xrange(x_range, y_range):
    text.object = f'x_range: {x_range}'


coastline = gv.feature.coastline
xy_range = hv.streams.RangeXY(source=coastline)
xy_range.add_subscriber(print_xrange)
text = pn.pane.Str('')

pn.Column(coastline, text).servable()
```

#### Stack traceback and/or browser JavaScript console output
No errors

#### Screenshots or screencasts of the bug in action

https://github.com/user-attachments/assets/78f01e1a-4045-426d-a17b-bc298c8b7678

**Comment by hoxbro** [comment]
Do you know if it is HoloViews or Geoviews release which broke it?

Maybe https://github.com/holoviz/geoviews/pull/722 is the culprit.

**Comment by hoxbro** [comment]
Easier to downgrade holoviews first.

**Comment by hoxbro** [comment]
Can you comment out these lines:

https://github.com/holoviz/geoviews/blob/256394bbe879ac3873bfc16e4b3ed1414d1635e7/geoviews/plotting/bokeh/callbacks.py#L99-L102

**Comment by TheoMathurin** [comment]
Removing these lines does solve the problem!

As an aside, I tried with holoviews 1.18.3 and geoviews 1.13.0 but by default it installed panel 1.5.2 which is not compatible with 1.18.3 it seems:

```
  File "/home/mathurin/miniconda3/envs/test-range/lib/python3.12/site-packages/holoviews/core/util.py", line 1634, in resolve_dependent_value
    from panel.depends import param_value_if_widget
ImportError: cannot import name 'param_value_if_widget' from 'panel.depends'
```

**Comment by TheoMathurin** [comment]
@hoxbro @ahuang11 

I don't know how to move forward on this one. I guess the solution is not to remove the line mentioned above, since the changes brought by #722 had a purpose of their own.

Currently everything relying on `RangeXY` in PlateCarree CRS is going to be affected, including datashader range updates.

**Comment by ahuang11** [comment]
@TheoMathurin can you try https://github.com/holoviz/geoviews/pull/756 and see if that fixes your issues?
